// Behaviour checks with a minimal DOM adapter; not a browser/layout test.
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const events = {};
const button = {attrs:{},addEventListener(k,v){events['button:'+k]=v},setAttribute(k,v){this.attrs[k]=v},focus(){this.focused=true}};
const root = {open:false,classList:{toggle(k,v){root.open=v},contains(){return root.open}}};
const sidebar = {inert:false,contains(){return false},querySelector(){return {focus(){sidebar.focused=true}}}};
const mobile = {matches:true,addEventListener(k,v){events['media:'+k]=v}};
const backdrop = {addEventListener(k,v){events['backdrop:'+k]=v}};
const source = fs.readFileSync('backend/public/assets/workspace.js','utf8');
const start = source.indexOf('  const root');
const end = source.indexOf('  const connectivityLabel');
vm.runInNewContext(source.slice(start,end),{window:{matchMedia(){return mobile}},document:{getElementById(){return sidebar},querySelector(s){return s==='[data-workspace]'?root:backdrop},querySelectorAll(){return [button]},addEventListener(k,v){events['document:'+k]=v}}});
assert.equal(sidebar.inert,true);
assert.equal(button.attrs['aria-expanded'],'false');
events['button:click']();
assert.equal(root.open,true);assert.equal(sidebar.inert,false);assert.equal(sidebar.focused,true);
events['document:keydown']({key:'Escape'});
assert.equal(root.open,false);assert.equal(sidebar.inert,true);assert.equal(button.focused,true);
events['button:click']();events['backdrop:click']();assert.equal(root.open,false);
mobile.matches=false;events['media:change']();assert.equal(sidebar.inert,false);
const rows=['task','home_service','referral_expiry'].map(kind=>({kind,hidden:false,getAttribute(){return kind},removeAttribute(){this.hidden=false},setAttribute(){this.hidden=true}}));
const chips=['all','task','home_service','referral_expiry'].map(kind=>({kind,pressed:'false',getAttribute(){return kind},setAttribute(k,v){this.pressed=v},addEventListener(k,v){this.click=v}}));
const empty={hidden:true,removeAttribute(){this.hidden=false},setAttribute(){this.hidden=true}};
const calendar={querySelector(){return empty},querySelectorAll(s){if(s==='[data-rph98-filter]')return chips;if(s.includes(':not'))return rows.filter(r=>!r.hidden);return rows}};
vm.runInNewContext(fs.readFileSync('backend/public/assets/rph98-calendar.js','utf8'),{document:{querySelector(){return calendar}}});
chips[2].click();assert.deepEqual(rows.map(r=>r.hidden),[true,false,true]);assert.equal(chips[2].pressed,'true');assert.equal(empty.hidden,true);
chips[0].click();assert.equal(rows.filter(r=>r.hidden).length,0);
console.log('PASS: mobile closed/open/Escape/backdrop/desktop states and calendar filters. DOM adapter only; browser layout remains unverified.');
