@php
    $serviceValue = $case->service_type instanceof \BackedEnum ? $case->service_type->value : $case->service_type;
    $statusValue = $case->status instanceof \BackedEnum ? $case->status->value : $case->status;
    $rtl = in_array(app()->getLocale(), ['fa','ar'], true);
@endphp
<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ $rtl ? 'rtl' : 'ltr' }}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ __('panel_case.case') }} {{ $case->public_reference }}</title>
<style>:root{font-family:system-ui,sans-serif;color:#17231f;background:#f5f7f6}*{box-sizing:border-box}body{margin:0}.shell{max-width:1100px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:22px}.btn{display:inline-flex;padding:9px 13px;border-radius:10px;border:1px solid #cbd6d1;background:#fff;color:#173b30;text-decoration:none;cursor:pointer;font:inherit}.primary{background:#134437;color:#fff;border-color:#134437}.danger{background:#fff7f7;color:#852f2f}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.card{background:#fff;border:1px solid #e0e6e3;border-radius:18px;padding:20px;margin-bottom:16px}.card h2{margin-top:0;font-size:1.15rem}.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.fact{background:#f8faf9;border-radius:11px;padding:12px}.fact small{display:block;color:#6b7873;margin-bottom:4px}.field{display:flex;flex-direction:column;gap:6px;margin:12px 0}input,select,textarea{font:inherit;border:1px solid #cad6d0;border-radius:9px;padding:9px 10px;width:100%}textarea{min-height:100px;resize:vertical}.item{padding:12px 0;border-bottom:1px solid #edf1ef}.item:last-child{border:0}.notice{padding:12px 14px;border-radius:10px;background:#eef5f1;margin-bottom:16px;display:none}.notice.error{background:#fff0f0;color:#8b2e2e}.policy{white-space:pre-line;padding:12px;background:#f8faf9;border-radius:9px;max-height:240px;overflow:auto}.review-text{white-space:pre-line;line-height:1.7}.muted{color:#697871;font-size:.9rem}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}@media(max-width:650px){.shell{padding:15px}.top{align-items:flex-start;flex-direction:column}}</style>
</head>
<body><main class="shell">
<header class="top"><div><div class="muted">{{ __('panel_case.case') }}</div><h1 style="margin:3px 0"><bdi>{{ $case->public_reference }}</bdi></h1></div><a class="btn" href="{{ route('panel',['locale'=>$locale]) }}">{{ __('panel_case.back') }}</a></header>
<div id="notice" class="notice" role="status"></div>
<section class="card"><div class="facts"><div class="fact"><small>{{ __('panel_case.service') }}</small>{{ $serviceValue }}</div><div class="fact"><small>{{ __('panel_case.status') }}</small>{{ $statusValue }}</div><div class="fact"><small>Version</small>{{ $case->version }}</div></div></section>

@if(!empty($shared))
<section class="card"><h2>{{ __('panel_case.details') }}</h2><div class="facts">
@foreach(['patient_name'=>__('panel_case.patient_name'),'patient_mobile'=>__('panel_case.patient_mobile'),'tehran_area'=>__('panel_case.area'),'preferred_contact_time'=>__('panel_case.contact_time'),'contact_reason'=>__('panel_case.contact_reason'),'budget_band'=>__('panel_case.budget'),'grant_expires_at'=>__('panel_case.grant_expires')] as $key=>$label)
@if(array_key_exists($key,$shared) && $shared[$key] !== null)<div class="fact"><small>{{ $label }}</small><bdi>{{ $shared[$key] }}</bdi></div>@endif
@endforeach
</div></section>
@endif

@if($roleKey === 'patient')
    @if($statusValue === 'draft')
    <section class="card"><h2>Submit request</h2><p class="muted">The exact approved coordination policy will be shown before submission.</p><button class="btn primary" type="button" onclick="submitCase()">Submit with consent</button></section>
    @endif
    <section class="card"><h2>{{ __('panel_case.upload') }}</h2><form id="upload-form"><div class="field"><label for="opg-file">{{ __('panel_case.file') }}</label><input id="opg-file" name="document" type="file" accept="image/jpeg,image/png" required></div><button class="btn primary" type="submit">{{ __('panel_case.upload') }}</button></form></section>
    <section class="card"><h2>{{ __('panel_case.documents') }}</h2>@forelse($documents as $document)<div class="item"><bdi>{{ $document->original_name }}</bdi> · {{ $document->status }} @if($document->status === 'approved')<a class="btn" target="_blank" rel="noopener" href="/api/v1/cases/{{ $case->id }}/documents/{{ $document->id }}/content">{{ __('panel_case.open_document') }}</a>@endif</div>@empty<p class="muted">{{ __('panel_case.no_items') }}</p>@endforelse</section>
    <section class="card"><h2>{{ __('panel_case.referrals') }}</h2>@forelse($referrals as $referral)<div class="item"><strong>{{ $referral->clinic_name }}</strong> · {{ $referral->status }} @if($referral->status === 'proposed')<div class="actions"><button class="btn primary" type="button" onclick="decideReferral('{{ $referral->id }}','{{ $referral->source_language }}','accepted')">{{ __('panel_case.accept') }}</button><button class="btn danger" type="button" onclick="decideReferral('{{ $referral->id }}','{{ $referral->source_language }}','declined')">{{ __('panel_case.decline') }}</button></div>@endif</div>@empty<p class="muted">{{ __('panel_case.no_items') }}</p>@endforelse</section>
    <section class="card"><h2>{{ __('panel_case.reviews') }}</h2>@forelse($reviews as $review)<article class="item"><strong>#{{ $review->revision_number }}</strong><p class="review-text"><b>{{ __('panel_case.image_adequacy') }}:</b> {{ $review->image_adequacy }}\n\n<b>{{ __('panel_case.observations') }}:</b> {{ $review->observations }}\n\n<b>{{ __('panel_case.limitations') }}:</b> {{ $review->limitations }}\n\n<b>{{ __('panel_case.options') }}:</b> {{ $review->options }}\n\n<b>{{ __('panel_case.next_step') }}:</b> {{ $review->recommended_next_step }}</p></article>@empty<p class="muted">{{ __('panel_case.no_items') }}</p>@endforelse</section>
@endif

@if($roleKey === 'coordinator')
<section class="card"><h2>{{ __('panel_case.coordinator_actions') }}</h2><div class="grid">
@if(count($allowedStatuses))<form id="status-form"><h3>{{ __('panel_case.change_status') }}</h3><div class="field"><select name="status" required>@foreach($allowedStatuses as $target)<option value="{{ $target->value }}">{{ $target->value }}</option>@endforeach</select></div><div class="field"><input name="reason" maxlength="1000" placeholder="{{ __('panel_case.reason') }}"></div><button class="btn primary">{{ __('panel_case.change_status') }}</button></form>@endif
<form id="assign-form"><h3>{{ __('panel_case.assign_clinician') }}</h3><div class="field"><select name="assignee_user_id" required>@foreach($eligibleClinicians as $clinician)<option value="{{ $clinician->id }}">{{ $clinician->name ?: '#'.$clinician->id }}</option>@endforeach</select></div><button class="btn primary" @disabled($eligibleClinicians->isEmpty())>{{ __('panel_case.assign_clinician') }}</button></form>
<form id="referral-form"><h3>{{ __('panel_case.propose_referral') }}</h3><div class="field"><select name="clinic_id" required>@foreach($clinics as $clinic)<option value="{{ $clinic->id }}">{{ $clinic->name }} · {{ $clinic->city }}</option>@endforeach</select></div><div class="field"><textarea name="reasoning" required maxlength="2000" placeholder="{{ __('panel_case.reason') }}"></textarea></div><button class="btn primary" @disabled($clinics->isEmpty())>{{ __('panel_case.propose_referral') }}</button></form>
</div><h3>Assignments</h3>@forelse($assignments as $assignment)<div class="item">{{ $assignment->purpose }} · {{ $assignment->name ?: '#'.$assignment->assignee_user_id }} · {{ $assignment->role }}</div>@empty<p class="muted">{{ __('panel_case.no_items') }}</p>@endforelse</section>
@endif

@if($roleKey === 'clinician')
<section class="card"><h2>{{ __('panel_case.documents') }}</h2>@forelse($documents as $document)<div class="item"><bdi>{{ $document->original_name }}</bdi> <a class="btn" target="_blank" rel="noopener" href="/api/v1/cases/{{ $case->id }}/documents/{{ $document->id }}/content">{{ __('panel_case.open_document') }}</a></div>@empty<p class="muted">{{ __('panel_case.no_items') }}</p>@endforelse</section>
<section class="card"><h2>{{ __('panel_case.clinician_actions') }}</h2><form id="review-form"><div class="field"><label>{{ __('panel_case.review_document') }}</label><select name="clinical_document_id" required>@foreach($documents as $document)<option value="{{ $document->id }}">{{ $document->original_name }}</option>@endforeach</select></div><input type="hidden" name="source_language" value="{{ $case->source_language }}"><div class="field"><label>{{ __('panel_case.image_adequacy') }}</label><textarea name="image_adequacy" required maxlength="1000"></textarea></div><div class="field"><label>{{ __('panel_case.observations') }}</label><textarea name="observations" required maxlength="5000"></textarea></div><div class="field"><label>{{ __('panel_case.limitations') }}</label><textarea name="limitations" required maxlength="3000"></textarea></div><div class="field"><label>{{ __('panel_case.options') }}</label><textarea name="options" required maxlength="5000"></textarea></div><div class="field"><label>{{ __('panel_case.next_step') }}</label><textarea name="recommended_next_step" required maxlength="3000"></textarea></div><button class="btn primary" @disabled($documents->isEmpty())>{{ __('panel_case.save_review') }}</button></form><h3>Draft reviews</h3>@forelse($draftReviews as $draft)<div class="item">#{{ $draft->revision_number }} · <button class="btn primary" type="button" onclick="publishReview('{{ $draft->id }}')">{{ __('panel_case.publish') }}</button></div>@empty<p class="muted">{{ __('panel_case.no_items') }}</p>@endforelse</section>
@endif
</main>
<script>
(() => {
 const csrf=document.querySelector('meta[name="csrf-token"]').content, locale=@json($locale), caseId=@json($case->id), caseVersion={{ (int)$case->version }}, sourceLanguage=@json($case->source_language);
 const notice=document.getElementById('notice');
 const show=(text,error=false)=>{notice.textContent=text;notice.className='notice'+(error?' error':'');notice.style.display='block';window.scrollTo({top:0,behavior:'smooth'});};
 const request=async(url,{method='GET',body=null,language=locale,multipart=false}={})=>{const headers={'Accept':'application/json','X-CSRF-TOKEN':csrf,'X-Locale':language};if(!multipart&&body!==null)headers['Content-Type']='application/json';const response=await fetch(url,{method,credentials:'same-origin',headers,body:body===null?null:(multipart?body:JSON.stringify(body))});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||data?.error?.code||data?.message||@json(__('panel_case.error')));return data;};
 window.submitCase=async()=>{try{const policy=await request('/api/v1/policies/case_coordination',{language:sourceLanguage});if(!confirm(policy.data.content))return;await request(`/api/v1/cases/${caseId}/submit`,{method:'POST',language:sourceLanguage,body:{version:caseVersion,policy_version:policy.data.version}});location.reload();}catch(e){show(e.message,true)}};
 const upload=document.getElementById('upload-form');if(upload)upload.addEventListener('submit',async e=>{e.preventDefault();try{const policy=await request('/api/v1/policies/opg_document_sharing',{language:sourceLanguage});if(!confirm(policy.data.content))return;await request(`/api/v1/cases/${caseId}/consent/opg_document_sharing`,{method:'POST',language:sourceLanguage,body:{policy_version:policy.data.version,content_hash:policy.data.content_hash,locale:sourceLanguage}});const form=new FormData(upload);await request(`/api/v1/cases/${caseId}/documents`,{method:'POST',language:sourceLanguage,body:form,multipart:true});location.reload();}catch(err){show(err.message,true)}});
 window.decideReferral=async(id,language,decision)=>{try{let body={decision};if(decision==='accepted'){const policy=await request('/api/v1/policies/referral_sharing',{language});if(!confirm(policy.data.content))return;body={...body,policy_version:policy.data.version,content_hash:policy.data.content_hash};}await request(`/api/v1/cases/${caseId}/referrals/${id}/decision`,{method:'POST',language,body});location.reload();}catch(e){show(e.message,true)}};
 const statusForm=document.getElementById('status-form');if(statusForm)statusForm.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(statusForm);try{await request(`/api/v1/staff/cases/${caseId}/status`,{method:'PATCH',body:{status:form.get('status'),reason:form.get('reason')||null,version:caseVersion}});location.reload();}catch(err){show(err.message,true)}});
 const assignForm=document.getElementById('assign-form');if(assignForm)assignForm.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(assignForm);try{await request(`/api/v1/staff/cases/${caseId}/assignments`,{method:'POST',body:{assignee_user_id:form.get('assignee_user_id'),purpose:'clinical_review',version:caseVersion}});location.reload();}catch(err){show(err.message,true)}});
 const referralForm=document.getElementById('referral-form');if(referralForm)referralForm.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(referralForm);try{await request(`/api/v1/staff/cases/${caseId}/referral-proposals`,{method:'POST',body:{clinic_id:form.get('clinic_id'),reasoning:form.get('reasoning'),source_language:sourceLanguage}});location.reload();}catch(err){show(err.message,true)}});
 const reviewForm=document.getElementById('review-form');if(reviewForm)reviewForm.addEventListener('submit',async e=>{e.preventDefault();const form=Object.fromEntries(new FormData(reviewForm));try{await request(`/api/v1/staff/cases/${caseId}/reviews`,{method:'POST',body:form,language:sourceLanguage});location.reload();}catch(err){show(err.message,true)}});
 window.publishReview=async id=>{try{await request(`/api/v1/staff/cases/${caseId}/reviews/${id}/publish`,{method:'POST',language:sourceLanguage,body:{}});location.reload();}catch(e){show(e.message,true)}};
})();
</script>
</body></html>
