<?php

return [
    'brand' => 'Royadarman', 'tagline' => 'Dental care-path guidance and coordination', 'nav_label' => 'Main navigation', 'language' => 'Language', 'menu' => 'Menu', 'cta' => 'Start a secure request', 'nav' => ['services' => 'Services', 'how' => 'How it works', 'about' => 'About', 'faq' => 'FAQ', 'contact' => 'Contact'], 'links' => ['opg' => 'Preliminary OPG review', 'home' => 'Home dentistry', 'referral' => 'Clinic referral and coordination', 'privacy' => 'Privacy', 'login' => 'Sign in'], 'footer_intro' => 'A clear route for dental guidance, coordination and referral, with clinical and non-clinical roles kept separate.', 'footer_services' => 'Services', 'footer_company' => 'Royadarman', 'footer_trust' => 'Trust & access', 'common_cta_title' => 'Ready for the next step?', 'common_cta_text' => 'The secure request path begins with mobile sign-in. Clinical information is accepted only inside the authenticated workspace.', 'trust_title' => 'Clear clinical boundaries',
    'home' => ['hero_title' => 'A clearer route to the dental care you need.', 'hero_text' => 'Royadarman receives your request, explains the available route, coordinates the hand-off, and brings in a licensed dentist whenever clinical judgement is required.', 'hero_primary' => 'Explore services', 'hero_secondary' => 'How Royadarman works', 'photo_alt' => 'Tehran skyline with Milad Tower. Location context only — not a Royadarman clinic.', 'photo_caption' => 'Tehran is the current operating city. The tower is a city landmark, not a Royadarman office.', 'map_title' => 'Your care path', 'map_subtitle' => 'From request to next step', 'map_steps' => [['title' => 'Clarify the need', 'text' => 'Service type, location and priorities.'], ['title' => 'Coordinate the route', 'text' => 'Referral, home service or OPG review.'], ['title' => 'Follow through', 'text' => 'Each hand-off has an accountable owner.']], 'services_title' => 'Three practical ways to start', 'services_intro' => 'Each service has its own page, scope and workflow.', 'all_services' => 'View all services', 'services' => ['referral' => ['title' => 'Guidance and clinic referral', 'text' => 'Coordination around your need, location and stated budget.'], 'home' => ['title' => 'Home dentistry in Tehran', 'text' => 'Coordination of suitable home dental services within Tehran city.'], 'opg' => ['title' => 'Preliminary OPG review', 'text' => 'A private path for review by a licensed dentist.']], 'process_title' => 'Designed for a safe hand-off from the beginning.', 'process_text' => 'Coordinators are not treating clinicians, and the platform owner has no implicit clinical-record access.', 'process_link' => 'See the full process', 'process_steps' => [['title' => 'Request', 'text' => 'Minimum necessary information is collected securely.'], ['title' => 'Coordination', 'text' => 'Service fit, area and availability are reviewed.'], ['title' => 'Clinical input when needed', 'text' => 'Clinical judgement stays with licensed dentists.'], ['title' => 'Follow-up', 'text' => 'The next step remains visible and traceable.']], 'trust_title' => 'Privacy is part of the service architecture.', 'trust_text' => 'Clinical documents stay outside the public web root and access is restricted and auditable.', 'trust_points' => ['No clinical documents are collected on public pages.', 'Clinic access is created only within an authorised scope.', 'A preliminary OPG review is not a final diagnosis.'], 'trust_link' => 'Privacy details', 'cta_title' => 'Start from the right page.', 'cta_text' => 'Explore services first, or move into the secure request workspace when ready.', 'faq_title' => 'Questions worth answering before you start', 'faq_intro' => 'We make the role, scope and clinical boundaries clear before a request is submitted.', 'faq_link' => 'All questions'],
    'pages' => [
        'services' => ['meta_title' => 'Royadarman Services | Dental Coordination', 'meta_description' => 'Clinic referral, Tehran home dentistry coordination and preliminary OPG review.', 'title' => 'Royadarman services', 'lead' => 'Three distinct service routes with controlled access and clear clinical boundaries.', 'services' => [['route' => 'public.referrals', 'icon' => 'icon-support.svg', 'title' => 'Guidance and clinic referral', 'text' => 'Coordination based on need, area and stated budget.'], ['route' => 'public.home-dentistry', 'icon' => 'icon-home.svg', 'title' => 'Home dentistry in Tehran', 'text' => 'Coordination for services that can appropriately be delivered at home.'], ['route' => 'public.opg', 'icon' => 'icon-opg.svg', 'title' => 'Preliminary OPG review', 'text' => 'Private image review by an assigned licensed dentist.']], 'sections' => [['title' => 'Which route fits?', 'body' => 'If you are unsure, describe the need in the secure request flow. Initial coordination helps choose a route; it does not diagnose.', 'items' => [['title' => 'Need treatment or a clinic', 'text' => 'Use guidance and referral.'], ['title' => 'Travel is difficult', 'text' => 'Ask whether a home service is suitable in Tehran.'], ['title' => 'You already have an OPG', 'text' => 'Use the preliminary review path to clarify the next step.']]]]],
        'how' => ['meta_title' => 'How Royadarman Works', 'meta_description' => 'How requests move from secure intake through coordination, clinical review where needed and follow-up.', 'title' => 'How Royadarman works', 'lead' => 'A defined chain of responsibility that keeps coordination separate from clinical treatment.', 'sections' => [['title' => 'From request to next step', 'body' => 'The flow starts with the minimum information required and moves into clinical data only when the service requires it.', 'items' => [['title' => 'Secure sign-in', 'text' => 'Mobile verification protects the patient workspace.'], ['title' => 'Coordination', 'text' => 'Service type, location, timing and budget preference are reviewed.'], ['title' => 'Clinical input only where required', 'text' => 'Licensed dentists handle clinical judgement.'], ['title' => 'Follow-through', 'text' => 'Referral or service hand-off remains traceable.']]], ['title' => 'Why separate roles?', 'body' => 'Platform operations and coordination should not silently become clinical authority. Diagnosis and treatment remain with licensed dentists.']]],
        'about' => ['meta_title' => 'About Royadarman', 'meta_description' => 'Royadarman is a dental guidance and coordination service, not a single clinic or treating clinician.', 'title' => 'About Royadarman', 'lead' => 'A coordination layer designed to reduce uncertainty between a patient need and an appropriate next step.', 'sections' => [['title' => 'Purpose', 'body' => 'Make the path clearer without blending commercial coordination with clinical decision-making.'], ['title' => 'Partner model', 'body' => 'Royadarman can coordinate with qualified clinics and dentists while limiting patient-data access to the authorised scope.'], ['title' => 'Current scope', 'body' => 'Home dentistry coordination is currently limited to Tehran city. Other routes depend on service type and network capacity.']]],
        'privacy' => ['meta_title' => 'Privacy & Security | Royadarman', 'meta_description' => 'How public and clinical information, consent and access are separated in Royadarman.', 'title' => 'Privacy and security', 'lead' => 'Clinical information should not travel through ordinary public channels. Royadarman separates public and clinical paths.', 'sections' => [['title' => 'Data minimisation', 'body' => 'Only information needed for a service or coordination task should be collected.'], ['title' => 'Clinical documents', 'body' => 'OPG images are held privately and require purpose-specific consent before relevant clinical access.'], ['title' => 'Partner access', 'body' => 'Sharing with a partner clinic should be consent-bound, limited in scope, time-limited and revocable.'], ['title' => 'Consent text is contextual', 'body' => 'The operational consent presented during a request is tied to its exact purpose and version.']]],
        'faq' => ['meta_title' => 'Frequently Asked Questions | Royadarman', 'meta_description' => 'Answers about services, OPG, home dentistry, referrals and privacy.', 'title' => 'Frequently asked questions', 'lead' => 'Clear answers about what Royadarman does and does not do.', 'sections' => [], 'faq_title' => 'Questions']],
    'faqs' => [['q' => 'Is Royadarman a clinic or doctor?', 'a' => 'No. It is a guidance, coordination and support service that can work with partner clinics and dentists.'], ['q' => 'Is an OPG review a diagnosis?', 'a' => 'No. It is preliminary and may need examination or additional imaging before a final diagnosis.'], ['q' => 'Where is home dentistry available?', 'a' => 'Current coordination is limited to Tehran city and depends on service suitability and provider capacity.'], ['q' => 'Can I send an OPG through a public messenger?', 'a' => 'No. Clinical documents should use the authenticated document path only.'], ['q' => 'When can a clinic access my information?', 'a' => 'Only within an authorised, purpose-specific sharing scope; a referral alone does not grant record access.'], ['q' => 'What if I do not know which service to choose?', 'a' => 'Start with the services page and describe your need in the secure request flow.']],
    'service_pages' => [
        'opg' => ['icon' => 'icon-opg.svg', 'label' => 'OPG', 'overview_title' => 'What this route is for', 'points' => ['JPEG/PNG image path with a defined size limit.', 'Files are not exposed through the public web root.', 'Clinical review is assigned to a licensed dentist.', 'The result is preliminary, not a final diagnosis.'], 'steps_title' => 'OPG review flow', 'steps' => [['title' => 'Sign in and consent', 'text' => 'The patient accepts the purpose-specific document policy.'], ['title' => 'Private upload', 'text' => 'The image enters private storage and the security-check path.'], ['title' => 'Licensed review', 'text' => 'Only an appropriately assigned clinician can publish the review.'], ['title' => 'Next-step guidance', 'text' => 'The preliminary review informs what should happen next.']], 'note_title' => 'Clinical boundary', 'note' => 'Remote image review does not replace an examination or a definitive diagnosis.'],
        'home_dentistry' => ['icon' => 'icon-home.svg', 'label' => 'Tehran', 'overview_title' => 'Home-service coordination', 'points' => ['Current coverage is Tehran city only.', 'Not every dental procedure is suitable for home delivery.', 'Suitability and capacity are checked before coordination.', 'Treatment is delivered by qualified providers.'], 'steps_title' => 'From request to home coordination', 'steps' => [['title' => 'Need and area', 'text' => 'The request and Tehran area are captured.'], ['title' => 'Suitability check', 'text' => 'The coordination team checks whether the service can be delivered at home.'], ['title' => 'Provider hand-off', 'text' => 'A qualified provider is coordinated when appropriate and available.']], 'note' => 'If the need requires clinic equipment or urgent assessment, a clinic route may be more appropriate.'],
        'referrals' => ['icon' => 'icon-support.svg', 'label' => 'Coordination', 'overview_title' => 'Referral around your needs', 'points' => ['Need and geography inform coordination.', 'Stated budget preference can be considered.', 'Referral does not guarantee a treatment outcome.', 'Patient data sharing requires a defined permission scope.'], 'steps_title' => 'Referral flow', 'steps' => [['title' => 'Needs and constraints', 'text' => 'Service, area, timing and budget preference are captured.'], ['title' => 'Available options', 'text' => 'The coordination team reviews suitable network capacity.'], ['title' => 'Proposed route', 'text' => 'A clinic or next step is suggested; clinical decisions remain with the dentist.']], 'note' => 'Royadarman facilitates coordination and does not promise clinical outcomes.'],
        'contact' => ['icon' => 'brand-mark.svg', 'label' => 'Support', 'overview_title' => 'Choose the right contact path', 'points' => ['Patient matters and clinical documents belong in the secure workspace.', 'Do not send OPG images through ordinary messaging channels.', 'General service questions should not include clinical records.'], 'steps_title' => 'Contact routes', 'steps' => [['title' => 'Patient request', 'text' => 'Use secure sign-in and the patient workspace.'], ['title' => 'Service question', 'text' => 'Review service and FAQ pages before starting a request.'], ['title' => 'Professional partnership', 'text' => 'Partner onboarding is handled through the organisational workflow when enabled.']], 'note' => 'This public page is not intended for clinical documents or detailed medical histories.'],
    ],
    'related_title' => 'Related paths',
    'photos' => [
        'tehran' => ['alt' => 'Tehran skyline with Milad Tower. Location context only — not a Royadarman clinic.', 'caption' => 'Tehran is the current operating city. The tower is a city landmark, not a Royadarman office.'],
        'coord' => ['alt' => 'An empty coordination desk used as an illustration of office work, not a Royadarman workplace.', 'caption' => 'Illustration of desk work. This is not a Royadarman office and does not show staff.'],
        'home' => ['alt' => 'A quiet apartment interior used to illustrate home dentistry coordination in Tehran. No people.', 'caption' => 'Home visits stay inside Tehran city. Not every procedure belongs at home.'],
        'opg' => ['alt' => 'A dental chair and instruments used to illustrate imaging workflow. Not a Royadarman treatment room.', 'caption' => 'A preliminary OPG reading is not a diagnosis and does not replace an examination.'],
        'support' => ['alt' => 'A headset on a desk used to illustrate support work. No faces.', 'caption' => 'Support conversations stay in the signed-in workspace. Clinical files do not belong on public channels.'],
        'about' => ['alt' => 'A stock portrait used only as a human presence. This person is not a Royadarman dentist, patient or employee.', 'caption' => 'Stock photography for atmosphere. It does not depict Royadarman staff.'],
    ],
];
